from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class FletArtifactsTests(unittest.TestCase):
    def test_streamlit_frontend_is_removed(self):
        self.assertFalse((ROOT / "app.py").exists())
        self.assertFalse((ROOT / "style.css").exists())
        requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")
        self.assertNotIn("streamlit", requirements.lower())

    def test_worker_uses_secret_env_and_restricts_github_io_origins(self):
        worker = (ROOT / "worker" / "index.js").read_text(encoding="utf-8")
        wrangler = (ROOT / "worker" / "wrangler.toml").read_text(encoding="utf-8")

        self.assertIn("env.PLANTNET_API_KEY", worker)
        self.assertNotIn("2b1004", worker)
        self.assertIn('"api-key": env.PLANTNET_API_KEY', worker)
        self.assertNotIn("Authorization", worker)
        self.assertIn("github.io", worker)
        self.assertIn("pages.dev", worker)
        self.assertIn("ALLOWED_ORIGIN", worker)
        self.assertIn("Access-Control-Allow-Origin", worker)
        self.assertIn("isFileLike", worker)
        self.assertIn("Worker proxy failed", worker)
        self.assertIn("URLSearchParams", worker)
        self.assertIn('name = "art-village-magnifier"', wrangler)
        self.assertIn('main = "index.js"', wrangler)

    def test_flet_app_has_magnifier_handle_callbacks(self):
        handle = (ROOT / "flet_app" / "magnifier_handle.py").read_text(encoding="utf-8")

        self.assertIn("class MagnifierHandle", handle)
        self.assertIn("on_switch", handle)
        self.assertIn("on_capture", handle)
        self.assertIn("capture_enabled", handle)
        self.assertNotIn("disabled=not capture_enabled", handle)
        self.assertIn("RadialGradient", handle)
        self.assertIn("tooltip=label", handle)
        self.assertNotIn("ft.border_radius.only", handle)

    def test_flet_main_uses_worker_and_camera(self):
        main = (ROOT / "flet_app" / "main.py").read_text(encoding="utf-8")

        self.assertIn("flet_camera", main)
        self.assertIn("run_app", main)
        self.assertIn("探險放大鏡啟動中", main)
        self.assertIn("探險放大鏡載入失敗", main)
        self.assertNotIn("重新啟動相機", main)
        self.assertIn("await initialize_camera()", main)
        self.assertIn("camera_ready", main)
        self.assertIn("capture_enabled=camera_ready", main)
        self.assertIn("POKEDEX_STORAGE_KEY", main)
        self.assertIn("LOCAL_CACHE_DIR", main)
        self.assertIn("tempfile.gettempdir()", main)
        self.assertIn("LOCAL_CACHE_PATH", main)
        self.assertIn("localStorage", main)
        self.assertIn("LOW_CONFIDENCE_THRESHOLD", main)
        self.assertIn("alternatives", main)
        self.assertIn("建議確認", main)
        self.assertIn("clear_legacy_snapshot_cache", main)
        self.assertNotIn("make_snapshot", main)
        self.assertNotIn("snapshot_to_capture", main)
        self.assertNotIn("retry_pending_snapshots", main)
        self.assertNotIn("離線暫存快照", main)
        self.assertNotIn("重送暫存快照", main)
        self.assertIn("ProgressRing", main)
        self.assertNotIn("藝素村手繪探險圖鑑", main)
        self.assertNotIn('section_label("🔍", "探險鏡頭")', main)
        self.assertIn("ft.RadioGroup", main)
        self.assertIn("WORKER_URL", main)
        self.assertIn("尚未設定 Cloudflare Pages 的 WORKER_URL", main)
        self.assertIn("worker_error_message", main)
        self.assertIn("Object.fromEntries", main)
        self.assertIn("mark_explorer_ready", main)
        self.assertIn("__artVillageReady", main)
        self.assertIn("辨識服務尚未部署", main)
        self.assertIn("PLANTNET_API_KEY", main)
        self.assertIn("正在初始化相機", main)
        self.assertIn("相機元件準備中，正在重試", main)
        self.assertIn("TimeoutException", main)
        self.assertIn("requests.post", main)
        self.assertIn("take_picture", main)
        self.assertIn("set_description", main)
        self.assertIn("GridView", main)
        self.assertIn("ft.run(main)", main)
        self.assertIn("FLET_SKIP_RUN", main)
        self.assertNotIn('__name__ == "__main__"', main)
        self.assertNotIn("text=f", main)
        self.assertIn("認識動物", main)
        self.assertIn("show_animal_card", main)
        self.assertIn("page.show_dialog", main)
        self.assertIn("content_area.content = animals_view", main)

    def test_cloudflare_pages_builds_and_patches_loader(self):
        build = (ROOT / "build.sh").read_text(encoding="utf-8")
        dev = (ROOT / "scripts" / "dev.ps1").read_text(encoding="utf-8")
        install_dev = (ROOT / "scripts" / "install-dev.ps1").read_text(encoding="utf-8")
        patcher = (ROOT / "scripts" / "patch_flet_loader.py").read_text(encoding="utf-8")
        wrangler = (ROOT / "wrangler.toml").read_text(encoding="utf-8")

        self.assertFalse((ROOT / ".github" / "workflows" / "deploy.yml").exists())
        self.assertIn("flet build web", build)
        self.assertIn("FLET_CLI_NO_RICH_OUTPUT", build)
        self.assertIn("--yes", build)
        self.assertIn("--route-url-strategy hash", build)
        self.assertIn("--web-renderer auto", build)
        self.assertIn("WORKER_URL", build)
        self.assertIn("PRE_BUILD_NOTES.md", build)
        self.assertIn("patch_flet_loader.py", build)
        self.assertIn("FLET_BUILD_ID", build)
        self.assertIn("_headers", build)
        self.assertIn("Cache-Control: no-store", build)
        self.assertIn('pages_build_output_dir = "flet_app/build/web"', wrangler)
        self.assertIn("flet_app/build/web/index.html", patcher)
        self.assertIn("探險家載入中", patcher)
        self.assertIn("explorer-pulse", patcher)
        self.assertIn("hasFletContent", patcher)
        self.assertIn("__artVillageReady", patcher)
        self.assertIn("45000", patcher)
        self.assertIn("flet-cache-buster", patcher)
        self.assertIn("appPackageUrl", patcher)
        self.assertIn("pyodideUrl", patcher)
        self.assertIn("flet run -d -w main.py", dev)
        self.assertIn("flet_app/requirements.txt", install_dev)


if __name__ == "__main__":
    unittest.main()
